### ISSUE TITLE
ruler offset

### ISSUE THREAD

**Issue by erwanp** [terranjp/matplotlib-tools#3]
Hello, 

Thanks for this nice project, I'm already using it and I hope it gets implemented in matplotlib!

There is a small problem when adding a Ruler on existing data. It rescales the axis to include the (0,0) origin point. This is due to your Ruler initialization and could be fixed with:

```
x0 = self.ax.get_xlim()[0]
y0 = self.ax.get_ylim()[0]
self.ruler, = self.ax.plot([x0, x0], [y0, y0], label='ruler', **lineprops)
... 
self.marker_a, = self.ax.plot(x0, y0, **used_markerprops)
self.marker_b, = self.ax.plot(x0, y0, **used_markerprops)
self.marker_c, = self.ax.plot(x0, y0, **used_markerprops)
```

**Comment by terranjp** [comment]
Awesome! I am glad it is proving useful. Thanks for the fix! I will incorporate it. I hope to submit the PR for it later this week.

**Comment by terranjp** [comment]
I just incorporated your fix in my distro. If you run into anything else let me know. I am going to polish up some of the docs and send the PR matplotlib devs in a couple days.
